# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39cc7b000bf9828f52e1a90e1bb549a5444fbc3be17ae87e4baa6691f2f4a53c4318a5fb9381a2fbf45010ba58b354b220155e002d246049b84b93543ae465be

test:
  secret_key_base: b233281f37a64bdf2b307ff7a3d499b87f8bcb723136cb6d9f7aa803961b98de8d4033e79c6619a9ae5f18c1ec5e4ecc6f6b67d141572a9f71b93eea8f59d01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
